version: "3"

services: 
  ldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      # - LDAP_SKIP_DEFAULT_TREE=yes
    volumes:
      - openldap_data:/bitnami/openldap

volumes:
  openldap_data: